# Generated by Django 4.1.5 on 2023-07-30 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CookieStand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True)),
                ("min_customers_per_hour", models.IntegerField(default=0)),
                ("max_customers_per_hour", models.IntegerField(default=0)),
                ("avg_cookies_per_sale", models.FloatField(default=0)),
                ("hourly_sales", models.JSONField(blank=True, default=list, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
